services:
  # ====================================================================================================================
  # POSTGRES SERVER - auth-user
  # ====================================================================================================================
  pg-docker-auth-user:
    image: postgres:16-alpine
    container_name: pg-auth-user
    environment:
      POSTGRES_DB: ead-authuser
      POSTGRES_PASSWORD: 1234567
    ports:
      - 5433:5432
    volumes:
      - ./.data/postgresql/data:/var/lib/postgresql/data
    networks:
      - dev-network

  # ====================================================================================================================
  # POSTGRES SERVER - ead-course
  # ====================================================================================================================
  pg-docker-ead-course:
    image: postgres:16-alpine
    container_name: pg-ead-course
    environment:
      POSTGRES_DB: ead-course
      POSTGRES_PASSWORD: 1234567
    ports:
      - 5432:5432
    volumes:
      - ./.data/postgresql/dataEadCourse:/var/lib/postgresql/dataEadCourse
    networks:
      - dev-network
  # ====================================================================================================================
  # POSTGRES SERVER - ead-notification
  # ====================================================================================================================
  pg-docker-ead-notification:
    image: postgres:16-alpine
    container_name: pg-ead-notification
    environment:
      POSTGRES_DB: ead-notification
      POSTGRES_PASSWORD: 1234567
    ports:
      - 5434:5432
    volumes:
      - ./.data/postgresql/dataEadNotification:/var/lib/postgresql/dataEadNotification
    networks:
      - dev-network
  # ====================================================================================================================
  # PGADMIN
  # ====================================================================================================================
  pgadmin-docker:
    image: dpage/pgadmin4
    container_name: dev-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: me@example.com
      PGADMIN_DEFAULT_PASSWORD: 1234567
    ports:
      - 5050:80
    volumes:
      - ./.data/pgadmin:/var/lib/pgadmin
    depends_on:
      - pg-docker-auth-user
    networks:
      - dev-network
  # ====================================================================================================================
  # RABBITMQ
  # ====================================================================================================================
  rabbitmq:
    image: rabbitmq:3.13-management
    container_name: rabbitmq
    restart: unless-stopped
    environment:
      RABBITMQ_DEFAULT_USER: 'guest'
      RABBITMQ_DEFAULT_PASS: 'guest'
    volumes:
      - ./.data/rabbitmq_data:/var/lib/rabbitmq/
    ports:
      - 15672:15672
      - 5672:5672
    networks:
      - dev-network
  # ====================================================================================================================
  # ELASTICSEARCH
  # ====================================================================================================================
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:9.5.4
    container_name: elasticsearch
    restart: unless-stopped

    environment:
      discovery.type: single-node
      xpack.security.enabled: true
      xpack.license.self_generated.type: basic
      ELASTIC_PASSWORD: 1234567
      ES_JAVA_OPTS: "-Xms512m -Xmx512m"

    ports:
      - "9200:9200"

    volumes:
      - ./.data/elasticsearch:/usr/share/elasticsearch/data

    networks:
      - dev-network
  # ====================================================================================================================
  # KIBANA
  # ====================================================================================================================
  kibana:
    image: docker.elastic.co/kibana/kibana:9.5.4
    container_name: kibana
    restart: unless-stopped

    depends_on:
      - elasticsearch

    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
      ELASTICSEARCH_USERNAME: kibana_system
      ELASTICSEARCH_PASSWORD: fd1D_VUNuLVH0-0oW10T

    ports:
      - "5601:5601"

    networks:
      - dev-network
  # ====================================================================================================================
  # FILEBEAT
  # ====================================================================================================================
  filebeat:
    image: docker.elastic.co/beats/filebeat:9.5.4
    container_name: filebeat
    restart: unless-stopped

    user: root

    depends_on:
      - elasticsearch
      - kibana

    volumes:
      - ./elastic/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro

      # Logs dos microserviços
      - ./logs:/logs:ro

      # Metadados Docker
      - /var/run/docker.sock:/var/run/docker.sock:ro

      # Dados internos do Filebeat
      - ./.data/filebeat:/usr/share/filebeat/data

    command:
      - filebeat
      - -e
      - --strict.perms=false

    networks:
      - dev-network
# ======================================================================================================================
# REDE
# ======================================================================================================================
networks:
  dev-network:
    driver: bridge
